### ISSUE TITLE
1 minute delay to update clock and outside temps

### ISSUE THREAD

**Issue by chrwei** [CuriousTech/ESP8266-HVAC#5]
I'm not sure if there's a reason to do that intentionally or not.  I defaulted min_save=255 to try it and it seems to work fine.  it still doesn't update until second()==1, but that might be a good thing.

**Comment by CuriousTech** [comment]
Good idea.  I wouldn't mind if it starts just a few seconds after boot.  It gets old waiting for that first read, but I hate to keep hitting the weather server too much during development.  Just try to stagger all the connections so you know which one is hanging it.  My PC connects ASAP and there's also the remote with 2 connections.  It can crash if they all try to connect at the same time.

**Comment by chrwei** [comment]
so I found your project in the beginning stages of making my own, and what I was tinkering with for remotes is to use UDP multicast.  it acts as a broadcast, so all nodes get all messages, but there's no hanging because it's UDP.  I'm still working on wrapping my head around your remotes process, but it looks like it sends to all anyway, so it seems a perfect fit as it's a single send instead of a loop.  this might fix the "too much at once" issue too.  my experiments also use NTP to keep the time synced which is also UDP, so no hanging there either.

**Comment by CuriousTech** [comment]
That's great!  I've been using TCP and it definitely has its drawbacks.  A lot of hanging on the connects, but once it gets going it's smooth.  I also use it with the web pages using JQuery and with my own Windows software though.  It would be nice to use both really.

**Comment by chrwei** [comment]
I have websockets going for the web pages and haven't noticed any hanging (and it's super fast to update), but that tends to be a manual load some seconds after it's booted.  of course all these libs adds flash use too. if I get a change tonight I'll post the code I've been playing with and drop a link here.

**Comment by CuriousTech** [comment]
Thanks Chris.  What do you think of this: https://github.com/me-no-dev/ESPAsyncTCP  
Most of the bad synchronous calls are in the client side connection.  The WebServer class for host is a nice design, and seems to take care of serving requests pretty well.

**Comment by chrwei** [comment]
the websocket lib I use can use that lib, but i haven't tried it yet.  https://github.com/Links2004/arduinoWebSockets

the 2 ar_\* ones here work together, the other 2 are just testing/demo projects https://github.com/chrwei/esp8266_experiments I'm pretty happy with the multicast and the websockets.  the rest needs some work...

you're WAY ahead of me in making an actual thermostat, I'm still learning a lot as well.

**Comment by CuriousTech** [comment]
I'll look it over in a few days.  Thanks Chris.

The old Spark-O-Stat was my first thermostat and I learned quite a bit from it.  I could improve the design a bit.  I have the parts to make the 5V version of the switching supply in my WiFi doorbell project which runs a bit cooler, and heat has been a real problem with anything onboard. The rest of it is fine as far as I'm concerned.

**Comment by CuriousTech** [comment]
@chrwei Okay, ESPAsyncWebServer's definitely good.  I modified my WiFi garage door project and it runs smoother.  The EventSource doesn't get params though, or I didn't see how, but I can do without it really.  But the switchover was easy enough, and the thermostat wouldn't take too much work.  Then maybe use WebSockets between the devices instead of the 2 one-way connections.
